menu:
  Home:
  Archives: archives
  About: about
  RSS: atom.xml

widgets:
- search
- category
- tag
- recent_posts
- tagcloud
- myWidget

excerpt_link: Read More

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid:
  facebook: false
  twitter: false
  google: false
  pinterest: false

fancybox: true

google_analytics: "UA-74187619-1"
rss:

# comment_provider: facebook
comment_provider: duoshuo
# Facebook comment
facebook:
  appid: 0
  comment_count: 5
  comment_width: 840
  comment_colorscheme: light

# 百度统计
baidu_tongji: true
# 百度验证
baidu_verifi: true
# google验证
google_verifi: true

# 多说评论
duoshuo: true 

# 多说分享
duoshuo_shared: true

# 不蒜子统计博客访问量
visit_statis_bsz: true

# google代码高亮
google_code_prettify: true

# http://blog.csdn.net/v123411739/article/details/45092871
swiftype: 
  enable: true

